import "dotenv/config";

const {
  MONGO_URI,
  JWT_SECRET,
  SENDGRID_API_KEY,
  BASE_URL,
  SENDGRID_TEMPLATE_ID_VERIFY,
  SENDGRID_TEMPLATE_ID_RESET,
  FROM_EMAIL,
  EMAIL_USER,
  EMAIL_PASS,
  TEMPLATE_ID_SENDERMAIL,
  API_KEY_SENDERMAIL,
} = process.env;

if (
  !MONGO_URI ||
  !JWT_SECRET ||
  !SENDGRID_API_KEY ||
  !BASE_URL ||
  !SENDGRID_TEMPLATE_ID_VERIFY ||
  !SENDGRID_TEMPLATE_ID_RESET ||
  !FROM_EMAIL ||
  !EMAIL_USER ||
  !EMAIL_PASS ||
  !TEMPLATE_ID_SENDERMAIL ||
  !API_KEY_SENDERMAIL
) {
  throw new Error("ENV is missing!");
}

export {
  MONGO_URI,
  JWT_SECRET,
  SENDGRID_API_KEY,
  BASE_URL,
  SENDGRID_TEMPLATE_ID_VERIFY,
  SENDGRID_TEMPLATE_ID_RESET,
  FROM_EMAIL,
  EMAIL_USER,
  EMAIL_PASS,
  TEMPLATE_ID_SENDERMAIL,
  API_KEY_SENDERMAIL,
};
